#!/usr/bin/env bash
# Deploy affected notebook projects to a Snowflake environment.
# Reads affected_projects.tsv (generated by deploy.py) and for each
# project: creates the stage, clears old files, uploads current files
# preserving directory structure, and refreshes the Notebook Project.
#
# Usage: bash deploy.sh <snowflake_connection>

set -euo pipefail

CONNECTION="$1"

run_sql() {
  echo "  SQL> $1"
  snow sql --connection "$CONNECTION" -q "$1"
}

while IFS=$'\t' read -r PROJECT_NAME PROJECT_PATH STAGE NPO
do
  echo ""
  echo "============================================================"
  echo "Deploying ${PROJECT_NAME} (connection: ${CONNECTION})"
  echo "============================================================"

  run_sql "CREATE STAGE IF NOT EXISTS ${STAGE} DIRECTORY = (ENABLE = TRUE);"

  echo "  SQL> REMOVE @${STAGE}/${PROJECT_NAME};"
  snow sql --connection "$CONNECTION" -q "
  REMOVE @${STAGE}/${PROJECT_NAME};
  " || true

  echo ""
  echo "  Uploading files:"
  while IFS= read -r file
  do
    ABS_PATH="$(python -c 'import os,sys; print(os.path.abspath(sys.argv[1]))' "$file")"
    REL_PATH="${file#${PROJECT_PATH}/}"
    STAGE_DIR="$(dirname "$REL_PATH")"

    if [ "$STAGE_DIR" = "." ]; then
      SQL="PUT 'file://${ABS_PATH}' @${STAGE}/${PROJECT_NAME} AUTO_COMPRESS=FALSE OVERWRITE=TRUE;"
    else
      SQL="PUT 'file://${ABS_PATH}' @${STAGE}/${PROJECT_NAME}/${STAGE_DIR} AUTO_COMPRESS=FALSE OVERWRITE=TRUE;"
    fi
    echo "  SQL> ${SQL}"
    snow sql --connection "$CONNECTION" -q "$SQL"
  done < <(find "$PROJECT_PATH" -type f \
    -not -path '*/__pycache__/*' \
    -not -path '*/.ipynb_checkpoints/*' \
    -not -name '.DS_Store')

  echo ""
  run_sql "CREATE NOTEBOOK PROJECT IF NOT EXISTS ${NPO} FROM '@${STAGE}/${PROJECT_NAME}';"

  run_sql "ALTER NOTEBOOK PROJECT ${NPO} ADD VERSION FROM '@${STAGE}/${PROJECT_NAME}';"

  echo ""
  echo "  Done: ${PROJECT_NAME}"
done < affected_projects.tsv
