#!/usr/bin/env bash
# Deploy affected notebook projects to a Snowflake environment.
# Reads affected_projects.tsv (generated by deploy.py) and for each
# project: creates the stage, clears old files, uploads current files
# preserving directory structure, and refreshes the Notebook Project.
#
# Usage: bash deploy.sh <snowflake_connection>

set -euo pipefail

CONNECTION="$1"

while IFS=$'\t' read -r PROJECT_NAME PROJECT_PATH STAGE NPO
do
  echo "Deploying ${PROJECT_NAME} (connection: ${CONNECTION})"

  snow sql --connection "$CONNECTION" -q "
  CREATE STAGE IF NOT EXISTS ${STAGE};
  "

  snow sql --connection "$CONNECTION" -q "
  REMOVE @${STAGE}/${PROJECT_NAME};
  " || true

  while IFS= read -r file
  do
    ABS_PATH="$(python -c 'import os,sys; print(os.path.abspath(sys.argv[1]))' "$file")"
    REL_PATH="${file#${PROJECT_PATH}/}"
    STAGE_DIR="$(dirname "$REL_PATH")"

    if [ "$STAGE_DIR" = "." ]; then
      snow sql --connection "$CONNECTION" -q "
      PUT 'file://${ABS_PATH}' @${STAGE}/${PROJECT_NAME}
      AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
      "
    else
      snow sql --connection "$CONNECTION" -q "
      PUT 'file://${ABS_PATH}' @${STAGE}/${PROJECT_NAME}/${STAGE_DIR}
      AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
      "
    fi
  done < <(find "$PROJECT_PATH" -type f \
    -not -path '*/__pycache__/*' \
    -not -path '*/.ipynb_checkpoints/*' \
    -not -name '.DS_Store')

  snow sql --connection "$CONNECTION" -q "
  CREATE NOTEBOOK PROJECT IF NOT EXISTS ${NPO}
  FROM '@${STAGE}/${PROJECT_NAME}';
  "

  snow sql --connection "$CONNECTION" -q "
  ALTER NOTEBOOK PROJECT ${NPO}
  ADD VERSION FROM '@${STAGE}/${PROJECT_NAME}';
  "
done < affected_projects.tsv
