#!/usr/bin/env bash
# Execute affected notebook projects in a Snowflake environment.
# Reads execute_projects.txt (generated by execute_dev.py) and runs
# each project's SQL file as a smoke test gate.
#
# Usage: bash execute_dev.sh <snowflake_connection>

set -euo pipefail

CONNECTION="$1"

while IFS= read -r PROJECT_NAME
do
  echo "Executing ${PROJECT_NAME} (connection: ${CONNECTION})"
  echo "---"
  cat "execute_${PROJECT_NAME}.sql"
  echo ""
  echo "---"
  snow sql --connection "$CONNECTION" -q "$(cat execute_${PROJECT_NAME}.sql)"
done < execute_projects.txt
